###################
#
# By: Ethan Gyllenhaal
# Last updated: 21Nov2020
#
# Script for calculating ABBA/BABA values for Foulehaio carunculatus (only D statistic here).
# Uses "bootstrapping_fuctions.R" by me and "jacknife.R" by Simon Martin.
## (found at https://github.com/simonhmartin/genomics_general)
# This includes all the comparison found in Table S4 of Mapel, Gyllenhaal et al. 2020.
# This will output raw values, ranges of values from bootstrapping, bootstrapped distribution, and bootstrapped p value.
# Naming scheme is messy, but looks like: *_[P1][P2][P3], where each "P" is a population.
# Positive values of D indicate gene flow between P2 and P3, and negative between P1 and P3.
#
##################


setwd('/path/to/directory')
# Load jacknife.R file to get block indices, from https://github.com/simonhmartin/genomics_general
source('path/to/jackknife.R')
# Load bootstrapping function
source("bootstrap_functions.R")
# Reads in gzipped, tab delimited data generated by script at https://github.com/simonhmartin/genomics_general
freq_table_ext = read.table("path/to/carunc_freqs_ext.tsv.gz", header=T, as.is=T)

#### Primary Comps
# Samoa <-> AF
D_boot_TongaNSamoaWFutuna <- calc_D_stat(freq_table_ext, "eueiki", "samoaW", "alofifutuna", 1000)
title(main = "(Eue-iki, West Samoa), Alofi-Futuna")

# Within Lau
D_boot_FulagaOgeaOno <- calc_D_stat(freq_table_ext, "fulaga", "ogea", "onoilau", 1000)
title(main = "(Fulaga, Ogea Levu), Ono-i-Lau")
D_boot_FutunaOgeaOno <- calc_D_stat(freq_table_ext, "alofifutuna", "ogea", "onoilau", 1000)
title(main = "(Futuna, Ogea Levu), Ono-i-Lau")
D_boot_OgeaFulagaMatuku <- calc_D_stat(freq_table_ext, "ogea", "fulaga", "matuku", 1000)
title(main = "(Ogea Levu, Fulaga), Matuku")


# Lau - Tonga
D_boot_FutunaTofuaOgea <- calc_D_stat(freq_table_ext, "alofifutuna", "tofua", "ogea", 1000)
title(main = "(Futuna, Tofua), Ogea Levu")
D_boot_FutunaEueikiOgea <- calc_D_stat(freq_table_ext, "alofifutuna", "eueiki", "ogea", 1000)
title(main = "(Futuna, Eue'iki), Ogea Levu")

# Samoa - Lau
D_boot_FutunaSamoaWOgea <- calc_D_stat(freq_table_ext, "alofifutuna", "samoaW", "ogea", 1000)
title(main = "(Futuna, Samoa W), Ogea Levu")

# Lau - AF
D_boot_OnoFulagaFutuna <- calc_D_stat(freq_table_ext, "onoilau", "fulaga", "alofifutuna", 1000)
title(main = "(Onoilau, Fulaga), Futuna")

#Samoa - Tonga
D_boot_EueikiTofuaSamoaW <- calc_D_stat(freq_table_ext, "eueiki", "tofua", "samoaW", 1000)
title(main = "(Eue'iki, Tofua), Samoa W")
D_boot_SamoaWSamoaETofua <- calc_D_stat(freq_table_ext, "samoaW", "samoaE", "tofua", 1000)
title(main = "(Samoa W, Samoa E), Tofua")




